<?php
namespace local_tnadvancemanage\util;

defined('MOODLE_INTERNAL') || die();

/**
 * Utility functions for managing question categories
 */
class question_category {
    /**
     * Gets the AI autogenerated question category name
     * 
     * @return string The category name
     */
    public static function get_question_category(): string {
        return 'ai_autogenerated';
    }
}