import { Metadata } from "next";
import React, { Suspense } from "react";

export const metadata: Metadata = {
  description: "Generated by Mochipan",
  icons: {
    icon: "/favicon.ico",
  },
  title: "uplearn",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang={ "en"}>
      <body>
        <Suspense>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
