name: Update README with Commit Info

on:
  push:
    branches:
      - main
      - develop

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest commit info
        id: commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
          echo "date=$(git log -1 --pretty=%ad --date=short)" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          if [ ! -f README.md ]; then
            echo "# Changelog" > README.md
            echo "\nThis file is automatically updated with commit information.\n" >> README.md
          fi
          echo "\n## Update $(date +"%Y-%m-%d")" >> README.md
          echo "- Commit: ${{ steps.commit.outputs.message }}" >> README.md
          echo "- Author: ${{ steps.commit.outputs.author }}" >> README.md
          echo "- Date: ${{ steps.commit.outputs.date }}" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update README with latest commit info [skip ci]"
          git push
